language: cpp
script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make && cd ..
    - test/consumer.sh build
    - build/test-asio-event && build/test-pool && build/test-serialize && build/test-threaded-conn-pool && build/test-traceable-list

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}" && mkdir $HOME/usr && export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.sh && chmod +x cmake-3.11.2-Linux-x86_64.sh
    - ./cmake-3.11.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    - wget "https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2" && tar -xjf boost_1_66_0.tar.bz2
    - cd boost_1_66_0 && echo "Building boost..." && ./bootstrap.sh --prefix=/usr --with-libraries=coroutine,system,atomic,date_time && sudo ./b2 install | grep -v '...skipped' | grep -v 'common.copy' && cd ..

addons:
  apt:
    sources:
      - george-edison55-precise-backports
